INSERT INTO clues (id, name) VALUES (61, 'Blood');
INSERT INTO clues (id, name) VALUES (62, 'Scorch marks');
INSERT INTO clues (id, name) VALUES (63, 'Bones');
INSERT INTO clues (id, name) VALUES (64, 'Fur');
INSERT INTO clues (id, name) VALUES (65, 'Body');
INSERT INTO clues (id, name) VALUES (66, 'Scratches');
INSERT INTO clues (id, name) VALUES (67, 'Tracks');
INSERT INTO clues (id, name) VALUES (68, 'Food');
INSERT INTO clues (id, name) VALUES (69, 'Wear');
INSERT INTO clues (id, name) VALUES (70, 'Writing');