INSERT INTO emotions (id, name) VALUES (31, 'Sense of dread');
INSERT INTO emotions (id, name) VALUES (32, 'Ominous feeling');
INSERT INTO emotions (id, name) VALUES (33, 'Feeling of being watched');
INSERT INTO emotions (id, name) VALUES (34, 'Feeling of familiarity');
INSERT INTO emotions (id, name) VALUES (35, 'Feeling of unnatural cold');
INSERT INTO emotions (id, name) VALUES (36, 'Sense of great age');
INSERT INTO emotions (id, name) VALUES (37, 'Feeling of insignificance');
INSERT INTO emotions (id, name) VALUES (38, 'Feeling of being unwelcome');
INSERT INTO emotions (id, name) VALUES (39, 'Sense of growing danger');
INSERT INTO emotions (id, name) VALUES (40, 'Sense of time running out');